//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
module PKtable {
	/**
	 * FILE: Lobby.xlsx SHEET: gameList
	 */
	export class gameList {
		id: number;
		gameId: number;
		gameDoc: string;
		gameDes: string;
		gameTheme: string;
		gameResConfigUrl: string;
		gameResRoot: string;
		preLoad: string;
		gameCodeUrl: string;
		gameIconUrl: string;
		gameShareUrl: string;
		markIconUrl: string;
		selectScene: number;

		GetType(): string { return 'table.gameList'; }
	}
}
