//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
module PKtable {
	/**
	 * FILE: 扑克表.xlsx SHEET: Sheet1 KEY: thisId
	 */
	export class PokerTableCard {
		cardId: number;
		thisId: number;
		name: string;
		type: number;
		icon: number;
		point: number;
		nocard: number;

		GetType(): string { return 'table.PokerTableCard'; }
	}
}
