//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
module PKtable {
	/**
	 * FILE: 表情礼物表.xlsx SHEET: 礼物 KEY: giftId
	 */
	export class TableGift {
		/**
		 * id
		 */
		giftId: number;
		/**
		 * name
		 */
		giftName: string;
		/**
		 * chips
		 */
		giftCost: number;
		/**
		 * charm
		 */
		giftCharm: number;

		GetType(): string { return 'table.TableGift'; }
	}
}
