//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
module PKtable {
	/**
	 * FILE: 语音表.xlsx SHEET: Sheet1 KEY: text
	 */
	export class TableVoice {
		cardId: number;
		/**
		 * 字符串
		 */
		text: string;

		GetType(): string { return 'table.TableVoice'; }
	}
}
