//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
module PKtable {
	/**
	 * FILE: 创建房间选项.xlsx SHEET: 玩法配置 KEY: id
	 */
	export class TablePlayTypeList {
		id: number;
		/**
		 * 描述
		 */
		desc: string;
		/**
		 * 分类
		 */
		playType: number;
		/**
		 * 玩法类型描述
		 */
		playTypedesc: string;
		/**
		 * 父类
		 */
		parent: number;
		/**
		 * 按钮样式
		 */
		buttonType: number;
		/**
		 * 互斥
		 */
		exclude: number[];

		GetType(): string { return 'table.TablePlayTypeList'; }
	}
}
