//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
module PKtable {
	/**
	 * FILE: 梅州麻将麻将番数.xlsx SHEET: config KEY: id*0x10000 + gameId
	 */
	export class TableMahjongMulti {
		id: number;
		gameId: number;
		multi: number;
		baohu: number;
		cartoon: string;
		name: string;
		type: string;
		disable: number[];

		GetType(): string { return 'table.TableMahjongMulti'; }
	}
}
