//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
module PKtable {
	/**
	 * FILE: 服务器返回状态码.xlsx SHEET: config
	 */
	export class TableServerReturnCode {
		id: number;
		desc: string;

		GetType(): string { return 'table.TableServerReturnCode'; }
	}
}
